replicaCount: 1

backend:
  image:
    repository: maryjane001/backend-app
    pullPolicy: IfNotPresent
    tag: "10016307834"

frontend:
  image:
    repository: maryjane001/frontend-app
    pullPolicy: IfNotPresent
    tag: "10016307834"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  host: chizzy01.duckdns.org
  paths:
    - path: /
      pathType: Prefix
      service:
        name: frontend-service
        port: 80
    - path: /api
      pathType: Prefix
      service:
        name: backend-service
        port: 3001
